version: "3"

services:
  ns-3:
    build: ns-3.29/
    command: /bin/bash ./waf --run "my_env"
    ports:
     - 5555:5565

  agents:
    build: agents/
    command: ./python main.py
    ports:
      - 5555:5565