FROM ubuntu:20.04

RUN apt-get upgrade
RUN apt-get update
RUN apt-get -y install gcc g++ python
RUN apt-get -y install software-properties-common

RUN add-apt-repository ppa:maarten-fonville/protobuf
RUN apt-get update

RUN apt-get -y install libzmq5 libzmq5-dev
RUN apt-get -y install libprotobuf-dev
RUN apt-get -y install protobuf-compiler

WORKDIR ./ns-3/
COPY . .
WORKDIR .
COPY config.json .
WORKDIR ./ns-3/
